apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-mysql
  labels:
    run: gowebapp-mysql
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gowebapp-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: gowebapp-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
          #TODO: replace value: rootpasswd with secretKeyRef
          #TODO: name is mysql
          #TODO: key is password
        image: image: gcr.io/${PROJECT_ID}/gowebapp-mysql:v1
        name: gowebapp-mysql
        ports:
        - containerPort: 3306
        #TODO add a livenessProbe which performs tcpSocket probe
        #aginst port 3306 with an initial
        # deay of 30 seconds, and a timeout of 2 seconds
        #TODO add a readinessProbe for tcpSocket port 3306 with a 25 second 
        #initial delay, and a timeout of 2 seconds
        #resources:
        #TODO define a resource request and limits based on VPA Recommender
